### ISSUE TITLE
it is not working with float

### ISSUE THREAD

**Issue by w3labkr** [spidoche/spidocheScaler#1]
Hi~

I find some two issue.

1) First
when i use this plugin with float and one page two tables, it is not  working.
temporarily, I solve a problem that modify css.

[css]
table{max-width:100%;float:left;}
[/css]

2) Second
it is not working ios simulator.
I can't solve this problem.

Thank you for share good plugins.
It is save my time ~

**Comment by spidoche** [comment]
Thanks for the report, I will try to fix this issue asap

**Comment by spidoche** [comment]
Float issue is fixed in 1.2.3. Thank for your help
